### ISSUE TITLE
Revoir la documentation

### ISSUE THREAD

**Issue by adrienpessu** [bttf-kotlin/kotlin-codelab-ktor#1]
- [x] Renommer les sous fichiers adoc avec un prefix de numérotation (0-requirements.adoc, ...)
- [x] Modifier les exercices : 
- exercice 1 en exercice 0 que l'on fait tous ensemble pour illustrer la gestion du null (step 0)
- exercice 1 (step 1) : ajout du filtre sur la liste dans la fonction prettier
- exercice 2 (step 2) : Modification de la fonction pour converture chaque chiffre de la date en nombre
- exercice 3 (step 3) : On ajoute ktor (Explication de la conf rapidement) et créer un point d'API REST /evrnts qui retourne notre liste d'Event
- exercice 4 (step 4) : Modifier la fonction de conversion pour retourner correctement la date
- exercice 5 (step 5) : Ajouter une extension à java.text.SimpleDateFormat ou java.util.Date avec notre fonction prettier
- exercice 6 : décompiler les fichiers class générés à partir des fichiers kt pour pour voir ce que le compilateur Kotlin. (donner la procédure avec intelliJ)
- [x] On fait toutes les modifications de la doc sur master et ensuite on reporte la doc sur toutes les branches

PS : Avant de débuter, j'ai envie de montrer le projet master (build.gradle et Main) pour montrer que c'est simple

**Comment by jabby** [comment]
Moi ça me convient bien. 
Tu veux le champ libre pour le moment pour monter le projet sur master ?

**Comment by adrienpessu** [comment]
Pour le moment, j'ai codé les étapes master, step0 à step4. Il me reste le step5 à coder.
Sur master, j'ai mis le build.gradle final pour que les gens puisse faire un ./gradlew build chez eux et avoir toutes les dépendances.
Et pour la doc, on peut se répartir les étapes si tu veux.

**Comment by adrienpessu** [comment]
J'ai modifié la doc pour prendre en compte le nouvelle enchainement des exercices.
Il reste à : 

- [ ] Faire une explication de kTor (Je veux bien le faire)
- [ ] Faire un § sur les extensions
- [ ] S'assurer de l'équilibre théorie / pratique et le bon enchainement du code lab
- [ ] Compléter des éléments de la doc qui pourrait l'être ou modifier les éléments obsolètes, s'il y en a.

**Comment by jabby** [comment]
Dans un premier temps je rejoue le codelab et je vois ce qui manque. Cela commence à dater la fois ou je l'ai fait tourner chez moi.

**Comment by jabby** [comment]
Je reviens vers toi car j'ai enfin rejoué le codelab. Je pense que certains points pourraient être améliorés. 
* systématiser les TUs (j'ai mis à jour la documentation pour ce point)
* mettre les TUs dans la classe EventUtil.kt plutôt que le main

Au niveau de l'exercice 2 j'ai toujours un peu de mal avec la solution.J'en ai une autre en tête. 
Je te propose de te la pousser sur une autre branche pour en discuter. Je ferais ça demain entre midi et 14h. 

Pour ce qui reste à faire, je me prends la partie extension. J'ai également quelques exercices complémentaires en tête si besoin.

**Comment by adrienpessu** [comment]
ok, j'ai rajouté un tu en step1. Y-a-t'il d'autre manque de TU?
J'ai renommé MainTest en EventUtilTest à partir de step 1

**Comment by adrienpessu** [comment]
- Comme je te l'avais dit, je relirai le tout jeudi après-midi. Mais si tu veux faire des modif vas-y. Une fois finie, je rajouterai la documentation à toutes les branches.
- On peut ajouter des exercices, j'avais pensé ajouter une connexion a une base de données mais c'est peut être un peu lourd ou alors on pourrait utiliser le client ktor et faire un appel à un json.
- On peut mettre l'extension sur String si tu veux, je l'avais mis sur SimpleDateFormat avant de la mettre sur Date. Je pense qu'on reste dans la logique dans les 3 cas
